package projetnew;
// Generated 10 f�vr. 2025, 14:52:05 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
public class Cours implements java.io.Serializable {

	private int idcours;
	private String code;
	private String nomcours;
	private Set classes = new HashSet(0);

	public Cours() {
	}

	public Cours(int idcours, String code, String nomcours) {
		this.idcours = idcours;
		this.code = code;
		this.nomcours = nomcours;
	}

	public Cours(int idcours, String code, String nomcours, Set classes) {
		this.idcours = idcours;
		this.code = code;
		this.nomcours = nomcours;
		this.classes = classes;
	}

	public int getIdcours() {
		return this.idcours;
	}

	public void setIdcours(int idcours) {
		this.idcours = idcours;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNomcours() {
		return this.nomcours;
	}

	public void setNomcours(String nomcours) {
		this.nomcours = nomcours;
	}

	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
