package projetnew;
// Generated 10 f�vr. 2025, 14:52:05 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant implements java.io.Serializable {

	private int idens;
	private Personne personne;
	private String matricule;
	private Set classes = new HashSet(0);

	public Enseignant() {
	}

	public Enseignant(int idens, String matricule) {
		this.idens = idens;
		this.matricule = matricule;
	}

	public Enseignant(int idens, Personne personne, String matricule, Set classes) {
		this.idens = idens;
		this.personne = personne;
		this.matricule = matricule;
		this.classes = classes;
	}

	public int getIdens() {
		return this.idens;
	}

	public void setIdens(int idens) {
		this.idens = idens;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
