package projetnew;
// Generated 10 f�vr. 2025, 14:52:05 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

	private int idetud;
	private Personne personne;
	private String numerocarte;
	private Set classes = new HashSet(0);

	public Etudiant() {
	}

	public Etudiant(int idetud, String numerocarte) {
		this.idetud = idetud;
		this.numerocarte = numerocarte;
	}

	public Etudiant(int idetud, Personne personne, String numerocarte, Set classes) {
		this.idetud = idetud;
		this.personne = personne;
		this.numerocarte = numerocarte;
		this.classes = classes;
	}

	public int getIdetud() {
		return this.idetud;
	}

	public void setIdetud(int idetud) {
		this.idetud = idetud;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public String getNumerocarte() {
		return this.numerocarte;
	}

	public void setNumerocarte(String numerocarte) {
		this.numerocarte = numerocarte;
	}

	public Set getClasses() {
		return this.classes;
	}

	public void setClasses(Set classes) {
		this.classes = classes;
	}

}
