package projetnew;
// Generated 10 f�vr. 2025, 14:52:05 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Personne implements java.io.Serializable {

	private int idpers;
	private String prenom;
	private String nom;
	private Integer age;
	private String adresse;
	private String login;
	private String mdp;
	private Set etudiants = new HashSet(0);
	private Set enseignants = new HashSet(0);

	public Personne() {
	}

	public Personne(int idpers, String prenom, String nom, String login, String mdp) {
		this.idpers = idpers;
		this.prenom = prenom;
		this.nom = nom;
		this.login = login;
		this.mdp = mdp;
	}

	public Personne(int idpers, String prenom, String nom, Integer age, String adresse, String login, String mdp,
			Set etudiants, Set enseignants) {
		this.idpers = idpers;
		this.prenom = prenom;
		this.nom = nom;
		this.age = age;
		this.adresse = adresse;
		this.login = login;
		this.mdp = mdp;
		this.etudiants = etudiants;
		this.enseignants = enseignants;
	}

	public int getIdpers() {
		return this.idpers;
	}

	public void setIdpers(int idpers) {
		this.idpers = idpers;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	public Set getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set etudiants) {
		this.etudiants = etudiants;
	}

	public Set getEnseignants() {
		return this.enseignants;
	}

	public void setEnseignants(Set enseignants) {
		this.enseignants = enseignants;
	}

}
